 const products =[
        {
            id: 1, 
            day: "Lunes",
            title: "RAVIOLES CON SALSA ROJA",
            colors:"Ravioles caseros de ricota",
            size: "fdfdfd",
            price: 1500,
            image: ["https://www.recetas-argentinas.com/base/stock/Recipe/47-image/47-image_web.jpg"],
            description:"Receta ",
            categoryId: 1,
        },
        {
            id:2,
            day: "Lunes",
            title:"ALBONDIGAS CON ARROZ",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://1.bp.blogspot.com/-Pyz77sdHIwI/VwUioYgY9nI/AAAAAAAAEog/htXRfYNNrEgTUQBzWX_7LvgGdzY668w8ACPcB/s1600/arroz-con-albondigas.jpg"],
            description:"cvfvfjdkf",
            categoryId: 1,
        },
        {
            id:3,
            day: "Lunes",
            title:"PASTEL DE PAPA + GUARNICIÓN",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://www.gastrotradicional.com/wp-content/webp-express/webp-images/doc-root/wp-content/uploads/2020/12/pastel-de-papa-3.jpg.webp"],
            description:"cvfvfjdkf",
            categoryId: 1,
        },
        {
            id:4,
            day: "Lunes",
            title:"GUISO DE CERDO",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://www.paulinacocina.net/wp-content/uploads/2021/09/goulash-noodles-eat-food-image-1.jpg"],
            description:"cvfvfjdkf",
            categoryId: 1,
        },
        {
            id:5,
            day: "Lunes",
            title:"MARINERAS + GUARNICIÓN",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://img-global.cpcdn.com/recipes/6e5740207b58d02a/640x640sq70/photo.webp"],
            description:"cvfvfjdkf",
            categoryId: 1,
        },
        {
            id:6,
            day: "Lunes",
            title:"ASADO A LA PARRILLA",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://locosxlaparrilla.com/wp-content/uploads/2015/02/Receta-recetas-locos-x-la-parrilla-locosxlaparrilla-receta-asado-salsa-criolla-asado-parrilla-asado-receta-asado-2.jpg"],
            description:"cvfvfjdkf",
            categoryId: 2,
        },
        {
            id:7,
            day: "Lunes",
            title:"Top Blanco",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://www.fondodeolla.com/files/image/36/36191/60ca7ebed1bc3.jpg"],
            description:"cvfvfjdkf",
            categoryId: 2,
        },
        {
            id:8,
            day: "Lunes",
            title:"Shorts Deportivo",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://vinomanos.com/wp-content/uploads/2021/03/pexels-engin-akyurt-3219483-min.jpg"],
            description:"cvfvfjdkf",
            categoryId: 2,
        },
        {
            id:9,
            day: "Lunes",
            title:"Top Blanco Deportivo",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://almacenonline.com.ar/wp-content/uploads/2019/07/cocacola1.5.jpg"],
            description:"cvfvfjdkf",
            categoryId: 3,
        },
        {
            id:10,
            day: "Lunes",
            title:"Top Deportivo con cierres",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://eyava.com/17236-large_default/gaseosa-seven-up-de-2-litros.jpg"],
            description:"cvfvfjdkf",
            categoryId: 3,
        },
        {
            id:9,
            day: "Lunes",
            title:"Top Blanco Deportivo",
            colors:"csdcsdc",
            size:"fdfdfd",
            price:1500,
            image:["https://eyava.com/17234-home_default/gaseosa-pepsi-de-2-litros.jpg"],
            description:"cvfvfjdkf",
            categoryId: 3
        }
];


export default {
    products
}